using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class UpdateSprite : MonoBehaviour
{
    public Sprite cardFace;
    public Sprite cardBack;

    private SpriteRenderer spriteRenderer;
    private Playable playable;
    private Solitaire solitaire;

    void Start()
    {
        // The deck generated by GenerateDeck() is always in a specific order
        // cardFaces[] also corresponds to that order, so we can match the sprite to its object
        List<string> deck = Solitaire.GenerateDeck();
        solitaire = FindObjectOfType<Solitaire>();

        int i = 0;

        foreach (string card in deck)
        {
            if (this.name == card)
            {
                cardFace = solitaire.cardFaces[i];
                break;
            }

            i++;
        }

        spriteRenderer = GetComponent<SpriteRenderer>();
        playable = GetComponent<Playable>();
    }

    void Update()
    {
        if (playable.isFaceUp == true)
        {
            spriteRenderer.sprite = cardFace;
        }
        else
        {
            spriteRenderer.sprite = cardBack;
        }
    }
}
